-- Whitelist paesi 12,5% (art. 6 c.1 + art. 11 c.4 lett. c D.Lgs 239/1996) — elenco completo
-- dal Decreto Min. Finanze 4 settembre 1996, testo consolidato con le modifiche del
-- Decreto 23/03/2017 (in vigore dal 03/04/2017), fornito dall'utente come PDF ufficiale.
-- Sostituisce il seed parziale FR/US di 0006 (inserito perche' erano gli unici paesi
-- serviti dai dati storici, con verificato=false in attesa del testo esatto).
--
-- paese_codice = ISO 3166-1 alpha-2, per matching con tax_instruments.issuer_country_code
-- (issuerCountryCode di IBKR SecurityInfo). Alderney e Herm sono elencati separatamente
-- nel decreto ma sono dipendenze della Bailiwick of Guernsey senza codice ISO 3166-1
-- proprio: IBKR non li riportera' mai come issuerCountryCode distinto da 'GG', quindi
-- sono inseriti con codice non-ISO puramente descrittivo (nessun matching operativo
-- possibile ne' necessario, dato che 'GG' li copre già).
--
-- Nota di manutenzione: l'art. 1-bis del decreto stesso prevede rimozioni successive per
-- singoli Stati/territori in caso di violazioni reiterate degli obblighi di cooperazione
-- (via decreto separato ex art. 11 c.5 D.Lgs 239/1996) — questo elenco va ri-verificato se
-- emergono titoli di stato di paesi non generalmente noti per essere rimossi dalla white
-- list, o periodicamente in occasione della dichiarazione annuale.

insert into public.tax_paesi_whitelist (paese_codice, descrizione, attivo, verificato) values
  ('AL', 'Albania', true, true),
  ('GG-ALD', 'Alderney (dipendenza Bailiwick of Guernsey, nessun codice ISO proprio — vedi GG)', true, true),
  ('DZ', 'Algeria', true, true),
  ('AD', 'Andorra', true, true),
  ('AI', 'Anguilla', true, true),
  ('SA', 'Arabia Saudita', true, true),
  ('AR', 'Argentina', true, true),
  ('AM', 'Armenia', true, true),
  ('AW', 'Aruba', true, true),
  ('AU', 'Australia', true, true),
  ('AT', 'Austria', true, true),
  ('AZ', 'Azerbaijan', true, true),
  ('BD', 'Bangladesh', true, true),
  ('BB', 'Barbados', true, true),
  ('BE', 'Belgio', true, true),
  ('BZ', 'Belize', true, true),
  ('BM', 'Bermuda', true, true),
  ('BY', 'Bielorussia', true, true),
  ('BA', 'Bosnia Erzegovina', true, true),
  ('BR', 'Brasile', true, true),
  ('BG', 'Bulgaria', true, true),
  ('CM', 'Camerun', true, true),
  ('CA', 'Canada', true, true),
  ('CL', 'Cile', true, true),
  ('CN', 'Cina', true, true),
  ('CY', 'Cipro', true, true),
  ('CO', 'Colombia', true, true),
  ('CG', 'Congo (Repubblica del Congo)', true, true),
  ('KR', 'Corea del Sud', true, true),
  ('CI', 'Costa d''Avorio', true, true),
  ('CR', 'Costa Rica', true, true),
  ('HR', 'Croazia', true, true),
  ('CW', 'Curacao', true, true),
  ('DK', 'Danimarca', true, true),
  ('EC', 'Ecuador', true, true),
  ('EG', 'Egitto', true, true),
  ('AE', 'Emirati Arabi Uniti', true, true),
  ('EE', 'Estonia', true, true),
  ('ET', 'Etiopia', true, true),
  ('RU', 'Federazione Russa', true, true),
  ('PH', 'Filippine', true, true),
  ('FI', 'Finlandia', true, true),
  ('FR', 'Francia', true, true),
  ('GE', 'Georgia', true, true),
  ('DE', 'Germania', true, true),
  ('GH', 'Ghana', true, true),
  ('JP', 'Giappone', true, true),
  ('GI', 'Gibilterra', true, true),
  ('JO', 'Giordania', true, true),
  ('GR', 'Grecia', true, true),
  ('GL', 'Groenlandia', true, true),
  ('GG', 'Guernsey', true, true),
  ('GG-HERM', 'Herm (dipendenza Bailiwick of Guernsey, nessun codice ISO proprio — vedi GG)', true, true),
  ('HK', 'Hong Kong', true, true),
  ('IN', 'India', true, true),
  ('ID', 'Indonesia', true, true),
  ('IE', 'Irlanda', true, true),
  ('IS', 'Islanda', true, true),
  ('IM', 'Isola di Man', true, true),
  ('KY', 'Isole Cayman', true, true),
  ('CK', 'Isole Cook', true, true),
  ('FO', 'Isole Faroe', true, true),
  ('TC', 'Isole Turks e Caicos', true, true),
  ('VG', 'Isole Vergini Britanniche', true, true),
  ('IL', 'Israele', true, true),
  ('JE', 'Jersey', true, true),
  ('KZ', 'Kazakistan', true, true),
  ('KG', 'Kirghizistan', true, true),
  ('KW', 'Kuwait', true, true),
  ('LV', 'Lettonia', true, true),
  ('LB', 'Libano', true, true),
  ('LI', 'Liechtenstein', true, true),
  ('LT', 'Lituania', true, true),
  ('LU', 'Lussemburgo', true, true),
  ('MK', 'Macedonia', true, true),
  ('MY', 'Malaysia', true, true),
  ('MT', 'Malta', true, true),
  ('MA', 'Marocco', true, true),
  ('MU', 'Mauritius', true, true),
  ('MX', 'Messico', true, true),
  ('MD', 'Moldova', true, true),
  ('MC', 'Monaco', true, true),
  ('ME', 'Montenegro', true, true),
  ('MS', 'Montserrat', true, true),
  ('MZ', 'Mozambico', true, true),
  ('NR', 'Nauru', true, true),
  ('NG', 'Nigeria', true, true),
  ('NU', 'Niue', true, true),
  ('NO', 'Norvegia', true, true),
  ('NZ', 'Nuova Zelanda', true, true),
  ('OM', 'Oman', true, true),
  ('NL', 'Paesi Bassi', true, true),
  ('PK', 'Pakistan', true, true),
  ('PL', 'Polonia', true, true),
  ('PT', 'Portogallo', true, true),
  ('QA', 'Qatar', true, true),
  ('GB', 'Regno Unito', true, true),
  ('CZ', 'Repubblica Ceca', true, true),
  ('SK', 'Repubblica Slovacca', true, true),
  ('RO', 'Romania', true, true),
  ('KN', 'Saint Kitts e Nevis', true, true),
  ('VC', 'Saint Vincent e Grenadine', true, true),
  ('WS', 'Samoa', true, true),
  ('SM', 'San Marino', true, true),
  ('VA', 'Santa Sede', true, true),
  ('SN', 'Senegal', true, true),
  ('RS', 'Serbia', true, true),
  ('SC', 'Seychelles', true, true),
  ('SG', 'Singapore', true, true),
  ('SX', 'Sint Maarten', true, true),
  ('SY', 'Siria', true, true),
  ('SI', 'Slovenia', true, true),
  ('ES', 'Spagna', true, true),
  ('LK', 'Sri Lanka', true, true),
  ('US', 'Stati Uniti d''America', true, true),
  ('ZA', 'Sud Africa', true, true),
  ('SE', 'Svezia', true, true),
  ('CH', 'Svizzera', true, true),
  ('TJ', 'Tagikistan', true, true),
  ('TW', 'Taiwan', true, true),
  ('TZ', 'Tanzania', true, true),
  ('TH', 'Thailandia', true, true),
  ('TT', 'Trinitad e Tobago', true, true),
  ('TN', 'Tunisia', true, true),
  ('TR', 'Turchia', true, true),
  ('TM', 'Turkmenistan', true, true),
  ('UA', 'Ucraina', true, true),
  ('UG', 'Uganda', true, true),
  ('HU', 'Ungheria', true, true),
  ('UY', 'Uruguay', true, true),
  ('UZ', 'Uzbekistan', true, true),
  ('VE', 'Venezuela', true, true),
  ('VN', 'Vietnam', true, true),
  ('ZM', 'Zambia', true, true)
on conflict (paese_codice) do update set
  descrizione = excluded.descrizione,
  attivo = excluded.attivo,
  verificato = excluded.verificato;
